#! /bin/bash

help_doc () {
    cat << help
用法：
repeat-string <印出內容> <重複次數> [最長輸出字元組數]

  印出內容： 不得為空
  重複次數： 必須大於等於 0
  最長輸出字元組數：
      > 0 : 從左邊向右 計算字元數
      = 0 : 不輸出
      < 0 : 從右邊向左 計算字元數
help
    exit 0;
}

( [[ -z $1 ]] || [[ ! $2 =~ ^[0-9]+$ ]] ) && help_doc;

eval "printf '$1%.0s' {1..$2};" | (
    if [[ $3 =~ ^[0-9]+$ ]]; then
        head --byte $3;
    elif [[ $3 =~ ^-[0-9]+$ ]]; then
        tail --byte $3;
    else
	    cat
    fi
)
